name: Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up wasm pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: wasm-pack build --verbose --all-features
    - name: Build website
      run: |
        cd web
        yarn
        yarn run build
    - name: Run tests
      run: |
        cd web
        yarn playwright install
        yarn run test
    - name: Run linter
      run: |
        cd web
        yarn run lint
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-artifacts
        path: web/dist/*
