name: Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up wasm pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: wasm-pack build --verbose --all-features
    - name: Build website
      run: |
        cd web
        yarn
        yarn run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-artifacts
        path: web/dist/*
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web/dist
        token: {{ secrets.DEPLOYMENT_ACCESS_TOKEN }}
        branch: main
        repository-name: sii-decode/sii-decode.github.io
        single-commit: true
        force: true
        clean: true
